apiVersion: apps/v1
kind: Deployment
metadata:
  name: loops
  labels:
    service: loops
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loops
  template:
    metadata:
      labels:
        service: loops
    spec:
      containers:
      - name: loops
        image: loops
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loops
  labels:
    service: loops
spec:
  selector:
    service: prod
  type: LoadBalancer    
  ports:
  - name: "http"
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        resources:
          requests:
            memory: "2Gi"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: SA_PASSWORD
          value: "Password1!"




